### ISSUE TITLE
PyPI package

### ISSUE THREAD

**Issue by tuke307** [hmarichal93/cstrd_ipol#2]
Hello, is it possible to publish a PyPI package? I would love to use the logic in other projects.

**Comment by hmarichal93** [comment]
Hi! yes, it is. I'll try to do it in the following days.

**Comment by tuke307** [comment]
Great! 
What would be the best approach to extract the tree disk from an image to have the white background that is needed for the analysis? Probably to train another yolo model to segment it?

**Comment by hmarichal93** [comment]
Hey,

I have created a new issue with the code for segmenting the background [here](https://github.com/hmarichal93/cstrd_ipol/issues/3). Is it ok if we follow the discussion there?

**Comment by tuke307** [comment]
ive created a pypi package for myself now. i refactored the code for my purposes there. maybe its helpful for somebody. i will keep updating it
[forked repo](https://github.com/tuke307/tree-disk-analyzer)
[pypi](https://pypi.org/project/tree-ring-analyzer)

**Comment by hmarichal93** [comment]
added pip installation procedure
